shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

packages:
  - clients/js
  - packages/*

onlyBuiltDependencies:
  - bigint-buffer
  - blake-hash
  - bufferutil
  - protobufjs
  - sharp
  - tiny-secp256k1
  - unrs-resolver
  - usb
  - utf-8-validate
